services:
  - type: web
    name: video-to-report
    env: python
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 1 --worker-class gevent --worker-connections 2 --timeout 0 --bind 0.0.0.0:$PORT --max-requests 10 --max-requests-jitter 5
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STEP_KEYWORD
        value: "cambiamos al siguiente paso"
    healthCheckPath: /health
    autoDeploy: true
